$(document).ready(function () {

    var cName = {
        array: [
            "All",
            "Afghanistan",
            "Africa",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua-and-Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia-and-Herzegovina",
            "Botswana",
            "Brazil",
            "British-Virgin-Islands",
            "Brunei",
            "Bulgaria",
            "Burkina-Faso",
            "Burundi",
            "CAR",
            "Cabo-Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Caribbean-Netherlands",
            "Cayman-Islands",
            "Chad",
            "Channel-Islands",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa-Rica",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czechia",
            "DRC",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican-Republic",
            "Ecuador",
            "Egypt",
            "El-Salvador",
            "Equatorial-Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Europe",
            "Faeroe-Islands",
            "Falkland-Islands",
            "Fiji",
            "Finland",
            "France",
            "French-Guiana",
            "French-Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong-Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle-of-Man",
            "Israel",
            "Italy",
            "Ivory-Coast",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nepal",
            "Netherlands",
            "New-Caledonia",
            "New-Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North-Macedonia",
            "Norway",
            "Oceania",
            "Oman",
            "Pakistan",
            "Palestine",
            "Panama",
            "Papua-New-Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto-Rico",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Réunion",
            "S-Korea",
            "Saint-Kitts-and-Nevis",
            "Saint-Lucia",
            "Saint-Martin",
            "Saint-Pierre-Miquelon",
            "San-Marino",
            "Sao-Tome-and-Principe",
            "Saudi-Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra-Leone",
            "Singapore",
            "Sint-Maarten",
            "Slovakia",
            "Slovenia",
            "Somalia",
            "South-Africa",
            "South-America",
            "South-Sudan",
            "Spain",
            "Sri-Lanka",
            "St-Barth",
            "St-Vincent-Grenadines",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Trinidad-and-Tobago",
            "Tunisia",
            "Turkey",
            "Turks-and-Caicos",
            "UAE",
            "UK",
            "US-Virgin-Islands",
            "USA",
            "Uganda",
            "Ukraine",
            "Uruguay",
            "Uzbekistan",
            "Vatican-City",
            "Venezuela",
            "Vietnam",
            "Western-Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ]
    }

    var k = 0;
    while (k < cName.array.length) {
        casesCovid(cName.array[k]);
        k = k + 1;
    }

    function numberWithCommas(number) {
        if (number != null) {
            var parts = number.toString().split(".");
            parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
            return parts.join(".");
        }

    }

    function casesCovid(namec) {
        $.ajax({
            "async": true,
            "crossDomain": true,
            "url": `https://covid-193.p.rapidapi.com/statistics?country=${namec}`,
            "method": "GET",
            "headers": {
                "x-rapidapi-host": "covid-193.p.rapidapi.com",
                "x-rapidapi-key": "dbd734df9dmshdec75273513b267p1d51e4jsn2aa6ba8bedf3"
            },
            success: function (resp, status) {

                if (status == "success") {
                    var a = resp;
                    if (a) {

                        // console.log(a);

                        var active = numberWithCommas(a.response[0].cases.active);
                        var deaths = numberWithCommas(a.response[0].deaths.total);
                        var recovered = numberWithCommas(a.response[0].cases.recovered);


                        $(`.t-active-cases.${namec}`).text(active);
                        $(`.t-death-cases.${namec}`).text(deaths);
                        $(`.t-recovered-cases.${namec}`).text(recovered);

                    }

                }
            },
            error: function () {
                alert("countryName Unable to load data !!");
            }
        });
    }
});